version: 2

sources:
  - name: tpcds
    database: wcd_analytic_eng_capstone
    schema: raw
    tables:
      - name: call_center
        columns:
          - name: cc_call_center_sk
            tests:
              - unique
              - not_null
          - name: cc_call_center_id
            tests:
              - not_null
          - name: cc_open_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: cc_closed_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
      - name: catalog_page
        columns:
        - name: cp_catalog_page_sk
          tests:
            - unique
            - not_null
        - name: cp_catalog_page_id
          tests:
            - not_null
        - name: cp_start_date_sk
          tests:
            - relationships:
                to: source('tpcds','date_dim')
                field: d_date_sk
        - name: cp_end_date_sk
          tests:
            - relationships:
                to: source('tpcds','date_dim')
                field: d_date_sk
      - name: catalog_sales
        columns:
          - name: cs_item_sk
            tests: 
              - unique
              - not_null
              - relationships:
                  to: source('tpcds','item')
                  field: i_item_sk
          - name: cs_order_number
            tests: 
              - unique
              - not_null
          - name: cs_sold_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: cs_sold_time_sk
            tests:
              - relationships:
                  to: source('tpcds','time_dim')
                  field: t_time_sk
          - name: cs_ship_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: cs_bill_customer_sk
            tests:
              - relationships:
                  to: source('tpcds','customer')
                  field: c_customer_sk
          - name: cs_bill_cdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_demographics')
                  field: cd_demo_sk
          - name: cs_bill_hdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','household_demographics')
                  field: hd_demo_sk          
          - name: cs_bill_addr_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_address')
                  field: ca_address_sk
          - name: cs_ship_customer_sk
            tests:
              - relationships:
                  to: source('tpcds','customer')
                  field: c_customer_sk
          - name: cs_ship_cdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_demographics')
                  field: cd_demo_sk
          - name: cs_ship_hdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','household_demographics')
                  field: hd_demo_sk
          - name: cs_ship_addr_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_address')
                  field: ca_address_sk
          - name: cs_call_center_sk
            tests:
              - relationships:
                  to: source('tpcds','call_center')
                  field: cc_call_center_sk
          - name: cs_catalog_page_sk
            tests:
              - relationships:
                  to: source('tpcds','catalog_page')
                  field: cp_catalog_page_sk
          - name: cs_ship_mode_sk
            tests:
              - relationships:
                  to: source('tpcds','ship_mode')
                  field: sm_ship_mode_sk
          - name: cs_warehouse_sk
            tests:
              - relationships:
                  to: source('tpcds','warehouse')
                  field: w_warehouse_sk
          - name: cs_promo_sk
            tests:
              - relationships:
                  to: source('tpcds','promotion')
                  field: p_promo_sk
      - name: customer
        columns:
          - name: c_customer_sk
            tests:
              - unique
              - not_null
          - name: c_customer_id
            tests:
              - not_null
          - name: c_current_cdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_demographics')
                  field: cd_demo_sk
          - name: c_current_hdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','household_demographics')
                  field: hd_demo_sk
          - name: c_current_addr_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_address')
                  field: ca_address_sk
          - name: c_first_shipto_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: c_first_sales_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: c_last_review_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
      - name: customer_address
        columns:
          - name: ca_address_sk
            tests:
              - unique
              - not_null
          - name: ca_address_id
            tests:
              - not_null
      - name: customer_demographics
        columns:
          - name: cd_demo_sk
            tests:
              - unique
              - not_null
      - name: date_dim
        columns:
          - name: d_date_sk
            tests:
              - unique
              - not_null
          - name: d_date_id
            tests:
              - not_null 
      - name: household_demographics
        columns:
          - name: hd_demo_sk
            tests:
              - unique
              - not_null
          - name: hd_income_band_sk
            tests:
              - relationships:
                  to: source('tpcds','income_band')
                  field: ib_income_band_sk
      - name: income_band
        columns:
          - name: ib_income_band_sk
            tests:
              - unique
              - not_null
      - name: item
        columns:
          - name: i_item_sk
            tests:
              - unique
              - not_null
          - name: i_item_id
            tests:
              - not_null
      - name: inventory
        columns:
          - name: inv_date_sk
            tests:
              - unique
              - not_null
              - relationships:
                  to: source('tpcds', 'date_dim')
                  field: d_date_sk
          - name: inv_item_sk
            tests:
              - unique
              - not_null
              - relationships:
                  to: source('tpcds', 'item')
                  field: i_item_sk
          - name: inv_warehouse_sk
            tests:
              - unique
              - not_null
              - relationships:
                  to: source('tpcds', 'warehouse')
                  field: w_warehouse_sk
      - name: promotion
        columns:
          - name: p_promo_sk
            tests:
              - unique
              - not_null
          - name: p_promo_id
            tests:
              - not_null
          - name: p_start_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: p_end_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: p_item_sk
            tests:
              - relationships:
                  to: source('tpcds','item')
                  field: i_item_sk
      - name: ship_mode
        columns:
          - name: sm_ship_mode_sk
            tests:
              - unique
              - not_null
          - name: sm_ship_mode_id
            tests:
              - not_null
      - name: time_dim
        columns:
          - name: t_time_sk
            tests:
              - unique
              - not_null
          - name: t_time_id
            tests:
              - not_null
          - name: t_time
            tests:
              - not_null
      - name: warehouse
        columns:
          - name: w_warehouse_sk
            tests:
              - unique
              - not_null
          - name: w_warehouse_id
            tests:
              - not_null
      - name: web_page
        columns:
          - name: wp_web_page_sk
            tests:
              - unique
              - not_null
          - name: wp_web_page_id
            tests:
              - not_null
          - name: wp_creation_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: wp_access_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: wp_customer_sk
            tests:
              - relationships:
                  to: source('tpcds','customer')
                  field: c_customer_sk
      - name: web_sales
        columns:
          - name: ws_item_sk
            tests: 
              - unique
              - not_null
              - relationships:
                  to: source('tpcds','item')
                  field: i_item_sk
          - name: ws_order_number
            tests: 
              - unique
              - not_null
          - name: ws_sold_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: ws_sold_time_sk
            tests:
              - relationships:
                  to: source('tpcds','time_dim')
                  field: t_time_sk
          - name: ws_ship_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: ws_bill_customer_sk
            tests:
              - relationships:
                  to: source('tpcds','customer')
                  field: c_customer_sk
          - name: ws_bill_cdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_demographics')
                  field: cd_demo_sk
          - name: ws_bill_hdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','household_demographics')
                  field: hd_demo_sk          
          - name: ws_bill_addr_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_address')
                  field: ca_address_sk
          - name: ws_ship_customer_sk
            tests:
              - relationships:
                  to: source('tpcds','customer')
                  field: c_customer_sk
          - name: ws_ship_cdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_demographics')
                  field: cd_demo_sk
          - name: ws_ship_hdemo_sk
            tests:
              - relationships:
                  to: source('tpcds','household_demographics')
                  field: hd_demo_sk
          - name: ws_ship_addr_sk
            tests:
              - relationships:
                  to: source('tpcds','customer_address')
                  field: ca_address_sk
          - name: ws_web_page_sk
            tests:
              - relationships:
                  to: source('tpcds','web_page')
                  field: wp_web_page_sk
          - name: ws_web_site_sk
            tests:
              - relationships:
                  to: source('tpcds','web_site')
                  field: web_site_sk
          - name: ws_ship_mode_sk
            tests:
              - relationships:
                  to: source('tpcds','ship_mode')
                  field: sm_ship_mode_sk
          - name: ws_warehouse_sk
            tests:
              - relationships:
                  to: source('tpcds','warehouse')
                  field: w_warehouse_sk
          - name: ws_promo_sk
            tests:
              - relationships:
                  to: source('tpcds','promotion')
                  field: p_promo_sk
      - name: web_site
        columns:
          - name: web_site_sk
            tests:
              - unique
              - not_null
          - name: web_site_id
            tests:
              - not_null
          - name: web_open_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
          - name: web_close_date_sk
            tests:
              - relationships:
                  to: source('tpcds','date_dim')
                  field: d_date_sk
